### ISSUE TITLE
Home Assistant Core update to 2023.5 broke integration

### ISSUE THREAD

**Issue by mf76130** [TheBrain8791/ha_awattar#7]
Hi,

Just updated to Home Assistant Core 2023.5 since that i get this error message
Logger: homeassistant.config_entries
Source: custom_components/awattar_energy_cost/__init__.py:26
Integration: Awattar Energy Cost ([documentation](https://github.com/TheBrain8791/ha_awattar), [issues](https://github.com/TheBrain8791/ha_awattar/issues))
First occurred: 06:13:14 (1 occurrences)
Last logged: 06:13:14

Error setting up entry Awattar (at) for awattar_energy_cost
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/awattar_energy_cost/__init__.py", line 26, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

br
michael

**Comment by gerione** [comment]
Seems to be linked to #5

**Comment by marklad** [comment]
Thank you @mf76130 for highlighting your problem. I am the author of #5 and will postpone my update to 2023.5 for some time.

I mostly use https://github.com/mampfes/ha_epex_spot instead of ha_awattar nowadays and have my own template sensors with a calculation including tax and service fees to have the final price per kWh.

The only thing I use this integration for is an apex card with a graph of the prices for today’s and tommorow’s prices.

**Comment by Marown** [comment]
@marklad can you maybe share your template sensors with your calculator with us/me? Thank you =)

**Comment by marklad** [comment]
> @marklad can you maybe share your template sensors with your calculator with us/me? Thank you =)

Hi @Marown ,
I hope this will help you, my templates are in german and I assume you will speak german too.

I have created an entity:

```
# Epex Spot für aWATTar umrechnen. 3 % Aufschlag + Netzkost 20 % MWst.
  - name: Awattar Preis Epex
    unique_id: "AwattarPreisEpex"
    icon: mdi:currency-eur
    unit_of_measurement: ct/kWh
    state: >
      {{ ( ( ( states('sensor.epex_spot_at_price') | float(0) ) / 1000 ) * states('input_number.awattar_aufschlag') | float(0) ) | round(5, default=0) }}
```

input_number.awattar_aufschlag = 1.236 (1 * 1,03 * 1,2) #3 Prozent Aufschlag + 20 % MWst.

I put this in a number so that I can change it quickly without having to update all my entities If awattar changes their prices.

I also have an automation which activates when "Awattar Preis Epex“ changes state (happens once per hour) then a service to change a numeric value is called (doesn't work in visual editor):

```
service: input_number.set_value
data:
  value: >-
    {{ (states('sensor.awattar_preis_epex')|float(6)) +
    states('input_number.awattar_aufschlag_netzgebuhren') | float(5) }}
target:
  entity_id: input_number.aktueller_strompreis_cent_kwh
```

 input_number.aktueller_strompreis_cent_kwh is then used in the energy dashboard and other instances to reflect the price including ALL costs except fixed monthly fees which are around 11 Euros (Leistungspauschale, Messentgelt, Gebrauchsabgabe (Energie + Netzentgelt)). You could add that too but I didn’t do it and only measure variable per kWh costs.
 
 I got 98,35 % accuracy in October in relation to monthly invoice.

Edit: I don’t use the ha_awattar integration anymore, also switched to Epex entities in my apex cards.

**Comment by J0s3f** [comment]
How do you calculate the awattar_aufschlag_netzgebuhren value @marklad

**Comment by marklad** [comment]
> How do you calculate the awattar_aufschlag_netzgebuhren value @marklad

thanks for asking! I forgot to mention it. It is a number input helper, which at the time of my writing back in December was "0,05 + 0,0059 + 0,001“ == 0,0801 ( that’s the total of Netzgebühren per kWh of Wiener Netze). There was a price increase in January but I have not adjusted it yet I have to wait for the invoice I get in a couple of days.

I hope that helps!
